apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ocp-ci-analysis
spec:
  entrypoint: entrypoint
  templates:
    - name: entrypoint
      steps:
        - - name: metrics
            template: metrics

    - name: metrics
      dag:
        tasks:
          - name: number-of-flakes
            template: notebook-executor
            arguments:
              parameters:
                [{ name: notebook, value: data-sources/TestGrid/number_of_flakes.ipynb }]

          - name: persistent-failures
            template: notebook-executor
            arguments:
              parameters:
                [{ name: notebook, value: data-sources/TestGrid/persistent_failures_analysis.ipynb}]

          - name: test-pass-failures
            template: notebook-executor
            arguments:
              parameters:
                [{ name: notebook, value: data-sources/TestGrid/test_pass_failures.ipynb}]

    - name: notebook-executor
      inputs:
        parameters:
          - name: notebook
          - name: memory-limit
            value: 4Gi
      outputs:
        artifacts:
          - name: "{{inputs.parameters.notebook}}"
            path: "/mnt/data/notebooks/{{inputs.parameters.notebook}}"
            archive:
              none: {}
            s3:
              endpoint: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
              bucket: black-flake
              key: "production_data/rendered_notebooks/{{inputs.parameters.notebook}}"
              accessKeySecret:
                key: AWS_ACCESS_KEY_ID
                name: black-flake
              secretKeySecret:
                key: AWS_SECRET_ACCESS_KEY
                name: black-flake
      podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"memory": "{{inputs.parameters.memory-limit}}" }}}]}'
      container:
        image: ocp-ci-analysis:latest
        command: [./notebook-executor.sh]
        args:
          - "notebooks/{{inputs.parameters.notebook}}" # input
          - "/mnt/data/notebooks/{{inputs.parameters.notebook}}" # output
        workingDir: /opt/app-root/src
        volumeMounts:
          - name: local-data-storage
            mountPath: /mnt/data
        env:
          - name: LOCAL_DATA_PATH
            value: /mnt/data
          - name: RUN_IN_AUTOMATION
            value: "true"
          - name: S3_ENDPOINT_URL
            value: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
          - name: S3_PROJECT_KEY
            value: ""
          - name: S3_BUCKET
            value: black-flake
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: black-flake
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: black-flake
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi

  volumeClaimTemplates:
    - metadata:
        name: local-data-storage
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
